service: starkbank-backend

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  regions:
      development: us-east-1
      staging: us-east-1
      production: us-east-1
 
provider:
  name: aws
  runtime: python3.8
  stage: development
  region: us-east-1
  environment:
    LOG_LEVEL: INFO 
    STAGE: ${self:custom.stage}
    REGION: ${aws:region}
    ACCOUNT: ${aws:accountId}
    TZ: 'America/Sao_Paulo'
  lambdaHashingVersion: 20201221

package:
  individually: false
  exclude:
    - tests/**
    - node_modules/**
    - functions/**
    - README.md/
    - venv/**
    - env/**

functions:
  - ${file(functions/lambda_receive_webhook.yml)}
  - ${file(functions/lambda_assync_processing.yml)}
  
resources:
  - ${file(serverless_resources/sqs_sns.yml)}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  # - serverless-binary-cors
  - serverless-offline
