Resources:
  ################################# webhook assync process ############################################
  WebHookQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Sub starkbank-sqs-${self:custom.regions.${self:custom.stage}}-#{AWS::AccountId}-WebHookQueue
      MessageRetentionPeriod: 345600
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt WebHookQueueDLQ.Arn
        maxReceiveCount: 3
  WebHookQueueDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Sub starkbank-sqs-${self:custom.regions.${self:custom.stage}}-#{AWS::AccountId}-WebHookQueueDLQ
      MessageRetentionPeriod: 345600

  ################################# DeadLetterQueu Send random Invoices ############################################
  SendRandomInvoiceSNS:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt SendRandomInvoiceQueueDLQ.Arn
          Protocol: "sqs"
      TopicName: !Sub ${self:custom.regions.${self:custom.stage}}-SendRandomInvoiceSNS
  SendRandomInvoiceQueueDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Sub starkbank-sqs-${self:custom.regions.${self:custom.stage}}-#{AWS::AccountId}-SendRandomInvoiceQueueDLQ
      MessageRetentionPeriod: 345600

Outputs:
  # SNS queue arn and name
  OutputSendRandomInvoiceSNSArn:
    Description: Arn of the Topic that should be triggered errors
    Export:
      Name: !Sub '#{AWS::AccountId}-#{AWS::Region}-OutputSendRandomInvoiceSNSArn'
    Value: !Ref SendRandomInvoiceSNS
  OutputSendRandomInvoiceSNSTopicName:
    Description: TopicName of the Topic that should be triggered errors
    Export:
      Name: !Sub '#{AWS::AccountId}-#{AWS::Region}-OutputSendRandomInvoiceSNSTopicName'
    Value: !GetAtt SendRandomInvoiceSNS.TopicName    
  #SQS queue arn and name
  OutputWebHookQueue:
    Description: Arn SQS queue to control assync webhook process and retry structural verifications
    Export:
      Name: !Sub '#{AWS::AccountId}-#{AWS::Region}-OutputWebHookQueueArn'
    Value: !GetAtt WebHookQueue.Arn
  OutputSendRandomInvoiceQueueDLQ:
    Description: Arn SQS queue to control assync sended invoice process and retry structural verifications
    Export:
      Name: !Sub '#{AWS::AccountId}-#{AWS::Region}-OutputSendRandomInvoiceQueueDLQArn'
    Value: !GetAtt SendRandomInvoiceQueueDLQ.Arn